### ISSUE TITLE
PPTX Support

### ISSUE THREAD

**Issue by amorri40** [open-xml-templating/docxtemplater-image-module#11]
The image module seems to work perfectly when using DocxGen but when using PptxGen it gives the following error:

```
c:\cm3_\node_modules\docxtemplater-image-module\js\index.js:91
    rId = this.imgManager.loadImageRels().addImageRels(this.getNextImageName()
                                          ^
TypeError: Cannot call method 'addImageRels' of undefined
    at ImageModule.replaceTag (c:\cm3_\node_modules\docxtemplater-image-module\js\index.js:91:43)
    at ImageModule.handle (c:\cm3_\node_modules\docxtemplater-image-module\js\index.js:155:12)
    at ModuleManager.module.exports.ModuleManager.handle (c:\cm3_\node_modules\docxtemplater\js\moduleManager.js:46:15)
    at PptXTemplater.module.exports.XmlTemplater.handleModuleManager (c:\cm3_\node_modules\docxtemplater\js\xmlTemplater.js:92:31)
    at PptXTemplater.module.exports.XmlTemplater.render (c:\cm3_\node_modules\docxtemplater\js\xmlTemplater.js:163:18)
    at PptxGen.DocxGen.renderFile (c:\cm3_\node_modules\docxtemplater\js\docxgen.js:64:41)
    at PptxGen.DocxGen.render (c:\cm3_\node_modules\docxtemplater\js\docxgen.js:75:14)
    at Object.exports.templatiseDocument (c:\cm3_\bin\phantomjs\sfc_presentation\generate_sfc_presentation.js:51:7)
    at Object.<anonymous> (c:\cm3_\bin\phantomjs\sfc_presentation\generate_sfc_presentation.js:72:9)
    at Module._compile (module.js:456:26)
```

Code used:

```
doc=new PptxGen().attachModule(imageModule).load(content); //not working
doc=new DocxGen().attachModule(imageModule).load(content); //working
```

**Comment by edi9999** [comment]
The problem is because the module searches the images in the `word` folder 

    file=@zip.files["word/_rels/#{@endFileName}.xml.rels"] || @zip.files["word/_rels/document.xml.rels"]
	if file==undefined then return

See here : https://github.com/open-xml-templating/docxtemplater-image-module/blob/master/coffee/imgManager.coffee#L25-L26

To add support for pptx, we should be first checking to see if that file is a docx or pptx file, than modify all the occurences of `word` to `ppt\slides` I think.

Do you want to give it a try and make a pull request

**Comment by amorri40** [comment]
Yes I am working on it at the moment in my forked version :)
Although it required more changes than I thought and its still not quite working, it works if I specify a previous rId but it doesn't seem to find the new rId.
I'll continue to investigate tommorow

**Comment by edi9999** [comment]
Hi, just wanted to know if you made it work now ?

**Comment by amorri40** [comment]
Hey :) yes it works pretty well now, I'm using it to generate presentations with images on demand. I'm afraid I haven't had time to remove the xml dependency yet.

**Comment by raminahmadi1986** [comment]
Hi @amorri40  , could you give me an example of how I can add an image to my pptx file ?

**Comment by riteshputhran** [comment]
Hi Guys. i am using version 2.1.5 and getting the same issue. %image works with docx but not with pptx. 
is this fixed or is there any work around?

**Comment by edi9999** [comment]
No, the issue is still not resolved. There is pull request #11 which has some code quality issues (see comments).

**Comment by edi9999** [comment]
Since version 3.0.1, which has been released today, this module can insert images inside PPTX. Kudos to @MaxRcd !n
