### ISSUE TITLE
Error when source image not available

### ISSUE THREAD

**Issue by martinWalnut** [open-xml-templating/docxtemplater-image-module#34]
Hi, 
I get everything working pretty well, but there is still one thing.. 

In my documents, I insert images based on specific condition. Sometimes I would like to insert no image. When no condition is met a no image should be inserted i get an error, because the compiler probably gets empty string as image name and he can load nothing. 

This is my error

C:\Users\Mroz\Documents\falafel\node_modules\docxtemplater\js\scopeManager.js:71
      throw err;
      ^
 Error
    at Object.<anonymous> (C:\Users\Mroz\Documents\falafel\node_modules\docxtemplater\js\errors.js:9
:21)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Mroz\Documents\falafel\node_modules\docxtemplater\js\docUtils.js
:4:10)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Mroz\Documents\falafel\node_modules\docxtemplater\js\docxgen.js:
8:12)
    at Module._compile (module.js:398:26)

Got any ideas how to make image loading "optional" ?

**Comment by edi9999** [comment]
You could use a condition :

Write

{#loop}{%image}{/loop}

And you can set in your data 

```
{
  "loop": false
}
```

To not show the image (or true to show the image)

**Comment by martinWalnut** [comment]
I ll do some deeper reserch, but this approach does not work, for some reason..Maybe the problem is somewhere else, I ll let you know.

**Comment by edi9999** [comment]
I think you can also use the value `undefined` as the value for you tag, this replaces the xml with an empty paragraph

**Comment by martinWalnut** [comment]
both didnt work for some reason for me, maybe I have made some mistake somewhere, dunno. 

I solved this using a little hack - in my controller, when I come to the point, when I want no image, I simply set tagValue to 1px image path...
