### ISSUE TITLE
docxtemplater-image-module doesn't work

### ISSUE THREAD

**Issue by TRechkalov** [open-xml-templating/docxtemplater-image-module#43]
Hello!

I'm trying to make simple example of image module.

First I call:
```
npm install docxtemplater@1.X
npm install docxtemplater-image-module
```

Installed docxtemplater version is 1.2.1 and image-module 1.0.0.

I copy image module examples folder to the same directory.

Then I make app.js:

```
var fs = require('fs');
var DocxGen = require('docxtemplater');

var content = fs.readFileSync(__dirname + "/examples/imageExample.docx", "binary");

var ImageModule=require('docxtemplater-image-module');

var opts = {}
opts.centered = false;
opts.getImage=function(tagValue, tagName) {
    return fs.readFileSync(tagValue,'binary');
}

opts.getSize=function(img,tagValue, tagName) {
    return [150,150];
}

var imageModule=new ImageModule(opts);

var docx=new DocxGen()
    .attachModule(imageModule)
    .load(content)
    .setData({image:'examples/image.png'})
    .render()

buffer= docx
        .getZip()
        .generate({type:"nodebuffer"})

fs.writeFile("test.docx",buffer);

```

Then I get exception:

```
<path>\docxtemplater-from-scratch\node_modules\docxtemplater-image-module\js\index.js:85
			var tagXml = xmlTemplater.fileTypeConfig.tagsXmlArray[0];
			                                        ^

TypeError: Cannot read property 'tagsXmlArray' of undefined
    at ImageModule.replaceTag (<path>\docxtemplater-from-scratch\node_modules\docxtemplater-image-module\js\index.js:85:44)
    at ImageModule.handle (<path>\docxtemplater-from-scratch\node_modules\docxtemplater-image-module\js\index.js:167:10)
    at ModuleManager.module.exports.ModuleManager.handle (<path>\docxtemplater-from-scratch\node_modules\docxtemplater\js\moduleManager.js:46:15)
    at DocXTemplater.module.exports.XmlTemplater.handleModuleManager (<path>\docxtemplater-from-scratch\node_modules\docxtemplater\js\xmlTemplater.js:128:31)
    at DocXTemplater.module.exports.XmlTemplater.compile (<path>\docxtemplater-from-scratch\node_modules\docxtemplater\js\xmlTemplater.js:191:18)
    at DocXTemplater.module.exports.XmlTemplater.render (<path>\docxtemplater-from-scratch\node_modules\docxtemplater\js\xmlTemplater.js:139:17)
    at DocxGen.renderFile (<path>\docxtemplater-from-scratch\node_modules\docxtemplater\js\docxgen.js:65:41)
    at DocxGen.render (<path>\docxtemplater-from-scratch\node_modules\docxtemplater\js\docxgen.js:76:14)
    at Object.<anonymous> (<path>\docxtemplater-from-scratch\app.js:26:6)
    at Module._compile (module.js:435:26)
```

**Comment by edi9999** [comment]
At the top of the readme 

> This version is only compatible with docxtemplater version 2
